
base_dir: "./"
data_path: "/media/hd2/Colon/Data_GT_Annotaion"
pkl_normalize: "/media/hd1/home/Shared/CTC_CVIP/Software/DeepLearning/config/ctcNormalization.pkl"
output_dir: "models"
test_save_dir: "seg_out/"
saved_model_path: "/media/hd1/home/Shared/CTC_CVIP/Software/DeepLearning/models/Unet++/Unet++timm-resnest269e-val_dice=0.9825.ckpt"

seed: 400
train_bs: 2
valid_bs: 1
workers: 1
seq_len: 3

progress_bar_refresh_rate: 1000

early_stop:
    monitor: "val_loss"
    mode: "min"
    patience: 10
    verbose: 1

trainer:
    max_epochs: 100 #26
    min_epochs: 100 #26
    # max_steps: 100 #26
    # min_steps: 100 #26
    # val_check_interval: 1
    enable_progress_bar: True
    # log_every_n_steps: 100
    # check_val_every_n_epoch: 
    precision: "16-mixed"
    devices: 1

model:
    seg_model: "Unet"
    encoder_name: "timm-resnest26d"
    encoder_weights: "imagenet" #"instagram" #"imagenet"
    loss_smooth: 1.0
    in_channels: 1
    image_size: 512
    convLSTM_kSize: 3
    convLSTM_hidden_chs: [32, 16, 8] 
    optimizer_params:
        lr: 0.0001 #5
        weight_decay: 0.03 # #0.01, 0.02
    scheduler:
        name: "CosineAnnealingLR"
        params:
            CosineAnnealingLR:
                T_max: 2
                eta_min: 1.0e-6
                last_epoch: -1
            ReduceLROnPlateau:
                mode: "min"
                factor: 0.31622776602
                patience: 4
                verbose: True
